services:
  golang:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  golang-mysql:
    image: mysql:8.0.37-debian
    # container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    # ports:
    #   - '3307:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
